spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cactus
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8000