logging:
  config: 'classpath:log4j2.yml'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cactus
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8000